[package]
name = "mcrputil"
version = "0.0.0"
description = "Minecraft Resource Pack Util for encrypting, decrypting, signing and verifying resource packs."
edition = "2021"

[dependencies]
mimalloc = { version = "0.1.29", default-features = false }
clap = { version = "4.0.18", features = ["derive"] }
aes = "0.8.2"
cfb8 = "0.8.1"
serde = { version = "1.0.147", features = ["derive"] }
serde_json = "1.0.87"
rand = "0.8.5"
glob = "0.3.0"

[profile.release]
lto = true
panic = "abort"
codegen-units = 1

[target.'cfg(windows)'.build-dependencies]
winres = "0.1.12"
